# Generated by Django 6.0.4 on 2026-05-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('build', 'Стройка'), ('supply', 'Снабжение'), ('contract', 'Договоры'), ('estimate', 'Сметы'), ('sales', 'Продажи'), ('internal', 'Внутренняя')], default='build', max_length=20, verbose_name='Тип задачи'),
            preserve_default=False,
        ),
    ]
