# frontend/nginx.conf
server {
    listen 80;
    client_max_body_size 50M;
    # 1. Раздача статики React (Фронтенд)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Проксирование API-запросов к Django
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Проксирование админки Django
    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 4. Раздача статики и медиа Django (картинки, файлы, CSS админки)
    location /static/ {
        alias /app/static/;
    }

    location /media/ {
        alias /app/media/;
    }
}
