# Generated by Django 6.0.4 on 2026-06-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_post_news',
            field=models.BooleanField(default=False, verbose_name='Может писать новости'),
        ),
    ]
