services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: erp_db
      POSTGRES_USER: erp_user
      POSTGRES_PASSWORD: my_super_secret_password # Укажи свой пароль
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always

  backend:
    build: . 
    restart: always
    # ОПТИМИЗАЦИЯ 1: Явно ограничили Gunicorn двумя процессами
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --workers 2 --bind 0.0.0.0:8000 Mini_ERP.wsgi:application"
    volumes:
      - static_volume:/app/static
      - ./media:/app/media
    environment:
      - DB_HOST=db
      - DB_NAME=erp_db
      - DB_USER=erp_user
      - DB_PASSWORD=my_super_secret_password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery:
    build: .
    restart: always
    # ОПТИМИЗАЦИЯ 2: Воркер сбрасывает кэш RAM каждые 40 выполненных задач
    command: celery -A Mini_ERP worker -l info --max-tasks-per-child=40
    volumes:
      - ./media:/app/media  # ИСПРАВЛЕНИЕ: привели к стандарту бэкенда
    environment:
      - DB_HOST=db
      - DB_NAME=erp_db
      - DB_USER=erp_user
      - DB_PASSWORD=my_super_secret_password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  celery-beat:
    build: .
    restart: always
    command: celery -A Mini_ERP beat -l info
    volumes:
      - ./media:/app/media  # ИСПРАВЛЕНИЕ: привели к стандарту бэкенда
    environment:
      - DB_HOST=db
      - DB_NAME=erp_db
      - DB_USER=erp_user
      - DB_PASSWORD=my_super_secret_password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - backend
      - redis

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - static_volume:/app/static
      - ./media:/app/media:ro
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  # media_volume удален за ненадобностью